services:
  django:
    build: .
    env_file: ".env"
    container_name: django
    command: python store/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/store
    ports:
      - 8000:8000
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    env_file: ".env"
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

  redis:
    image: redis



volumes:
  pgdbdata: null
