# Generated by Django 5.1.2 on 2024-11-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_order_delivery_type_remove_order_products_and_more'),
        ('payment', '0003_deliverytype_order_orderproduct_orderstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='orders',
            field=models.ManyToManyField(to='payment.order', verbose_name='Заказы'),
        ),
        migrations.DeleteModel(
            name='DeliveryType',
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
