# Generated by Django 5.1.2 on 2024-11-19 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_deliverytype_order_orderproduct_orderstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.order'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='payment_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
