# Generated by Django 4.2.16 on 2024-11-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_orderpayment_order_alter_orderpayment_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='des',
            field=models.TextField(default='des', verbose_name='Описание'),
        ),
    ]
